CoinStats Production Merge
astroboyReloaded/CoinStats pull request #17
Opened 2023-05-05 22:40 UTC by astroboyReloaded

## For this project, I did the following:
- Create react app.
- Install all dependencies.
- Select API
- Set up components files and routes.
- Fetch data from [CoinGeckos free API](https://www.coingecko.com/en/api)
- Create `SearchBar` and `Conversion` filters.
- Style
- Write tests for components and main functions.

2023-05-06 04:43 UTC, AnselemOdims requested changes
### Hi @astroboyReloaded , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Good job including the snapshot tests, but please kindly include tests for the pure functions in your Redux code.
- [ ] Also, please kindly include user interaction and integration tests using React Testing Library

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-06 04:43 UTC, AnselemOdims commented on README.md
> +- [Live Demo Link](https://hello-microverse.netlify.app/) -->
- [ ] Please kindly include the actual deployment for this project. At this moment, this deployment is for the `Hello Microverse` project.

2023-06-27 21:02 UTC, zainsadaqat reviewed
# ❌ ❌ ❌Invalid Code Review Request ❌ ❌ ❌
# Hello @astroboyReloaded  👋  

## Something went wrong 

### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for this reason:

- ### You have submitted a project in which you received a required changes review and didn't get approval due to which you cannot use the same PR in the following weeks, but you need to use a fresh PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

<img src="https://media3.giphy.com/media/qWJuYxjY9UAFx5bmCm/giphy.gif"/>

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-27 21:10 UTC, astroboyReloaded commented
Hi, @zainsadaqat! Thank you for taking the time to review my project.
I don't think I understand what you're asking for. This is my project's code review. Yes, it did not get approved last time (which was a few weeks ago because I had to repeat the module, but it is the same project, the same review). I don't see why I would create a new PR. I'd appreciate it if you could explain further... Thank you again!

2023-06-27 21:16 UTC, closed without merging

2023-06-29 14:31 UTC, nicupop729 commented
Hi @astroboyReloaded,
I am Nicolae Pop, a Senior Code Reviewer.

Zain, your previous Code Reviewer, had to invalidate the review because there is a rule that if a PR is not approved, but a student requests a review in the following weeks using the same PR.

The reason behind this rule is to ensure that the first reviewer of the current week (@zainsadaqat in this case) is not bound by the previous review given weeks ago (in this case, the one given by @AnselemOdims). While reviewers are expected to provide consistent reviews, in the case of repeating a week, we want to have a completely fresh review from the first reviewer of the current week.

I hope this explanation makes sense.

Best of luck!